name: noise_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12.3
  - pip
  - pip:
      - contourpy==1.3.1
      - cycler==0.12.1
      - filelock==3.17.0
      - fonttools==4.56.0
      - fsspec==2025.3.0
      - jinja2==3.1.6
      - joblib==1.4.2
      - kiwisolver==1.4.8
      - librosa==0.10.2
      - llvmlite==0.44.0
      - markupsafe==3.0.2
      - matplotlib==3.10.1
      - mpmath==1.3.0
      - networkx==3.4.2
      - numba==0.61.0
      - numpy==2.1.3
      - packaging==24.2
      - pandas
      - openpyxl
      - seaborn
      - imageio==2.36.1
      - pillow==11.1.0
      - pyparsing==3.2.1
      - python-dateutil==2.9.0.post0
      - scikit-image==0.24.0
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - six==1.17.0
      - snntorch==0.9.4
      - sympy==1.13.1
      - threadpoolctl==3.5.0
      - torch==2.6.0
      - torchvision==0.21.0
      - tqdm==4.67.1
      - typing-extensions==4.12.2

